"""PR creation tool (MCP)."""
from typing import Dict, Any, List
import subprocess
from app.mcp.base import MCPTool


class PRCreatorTool(MCPTool):
    """Create a pull request with generated test cases."""
    
    def __init__(self):
        super().__init__(
            name="pr_creator",
            description="Create GitHub PR with test files",
            tool_type="high"
        )
    
    async def execute(
        self,
        workspace_path: str,
        repo_full_name: str,
        pr_number: int,
        test_cases: List[Dict[str, Any]],
        test_summary: Dict[str, Any],
        test_framework: Dict[str, Any],
        base_branch: str = "main"
    ) -> Dict[str, Any]:
        """Create PR with test cases."""
        from app.mcp.tools.mid_level.git_tools import GitCommitTool, GitPushTool
        from app.agents.business.github_agent import GithubAgent
        
        try:
            # Create a new branch for test cases
            branch_name = f"e2e-tests-pr-{pr_number}"
            
            # Create and checkout new branch
            subprocess.run(
                ["git", "-C", workspace_path, "checkout", "-b", branch_name],
                check=True,
                capture_output=True,
                timeout=60
            )
            
            # Commit test files
            commit_tool = GitCommitTool()
            commit_result = await commit_tool.execute(
                repo_path=workspace_path,
                message=f"Add E2E tests for PR #{pr_number}\n\nAuto-generated tests based on PR requirements.",
                files=None  # Add all changes
            )
            
            if not commit_result.get("success"):
                return {
                    "success": False,
                    "error": f"Failed to commit test files: {commit_result.get('error')}"
                }
            
            # Push to remote
            push_tool = GitPushTool()
            push_result = await push_tool.execute(
                repo_path=workspace_path,
                remote="origin",
                branch=branch_name
            )
            
            if not push_result.get("success"):
                return {
                    "success": False,
                    "error": f"Failed to push branch: {push_result.get('error')}"
                }
            
            # Create PR using GitHub client
            pr_body = f"""# Auto-generated E2E Tests

This PR adds E2E test cases based on PR #{pr_number}.

## Test Summary
- Total tests: {test_summary.get('total_tests', 0)}
- Passed: {test_summary.get('passed_count', 0)}
- Failed: {test_summary.get('failed_count', 0)}

## Test Framework
{test_framework.get('framework', 'N/A')} (confidence: {test_framework.get('confidence', 'N/A')})

## Generated Test Files
"""
            
            for case in test_cases:
                pr_body += f"- `{case.get('file_path', 'N/A')}`\n"
            
            pr_body += "\n---\n*This PR was automatically generated by QAgent*"
            
            github_client = GithubAgent()
            pr_result = await github_client.create_pr(
                repo_full_name=repo_full_name,
                title=f"[E2E Tests] Auto-generated tests for PR #{pr_number}",
                body=pr_body,
                head=branch_name,
                base=base_branch
            )
            
            if pr_result.get("success"):
                return {
                    "success": True,
                    "pr_number": pr_result.get("number"),
                    "pr_url": pr_result.get("url"),
                    "branch": branch_name
                }
            else:
                return {
                    "success": False,
                    "error": f"Failed to create PR: {pr_result.get('error')}"
                }
            
        except Exception as e:
            return {
                "success": False,
                "error": f"Error creating PR: {str(e)}"
            }
    
    def _get_input_schema(self) -> Dict[str, Any]:
        return {
            "type": "object",
            "properties": {
                "workspace_path": {"type": "string", "description": "Workspace path"},
                "repo_full_name": {"type": "string", "description": "Repository full name"},
                "pr_number": {"type": "integer", "description": "Original PR number"},
                "test_cases": {
                    "type": "array",
                    "description": "List of test case objects",
                    "items": {"type": "object"}
                },
                "test_summary": {
                    "type": "object",
                    "description": "Test execution summary"
                },
                "test_framework": {
                    "type": "object",
                    "description": "Detected test framework info"
                },
                "base_branch": {
                    "type": "string",
                    "description": "Base branch for PR",
                    "default": "main"
                }
            },
            "required": ["workspace_path", "repo_full_name", "pr_number", "test_cases", "test_summary", "test_framework"]
        }
